import os
import json
from typing import Dict, Any, Optional, List

HTML_TEMPLATE = """
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Clinical Trial Radar — Feasibility Snapshot</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 20px; }}
    pre {{ background: #f6f6f6; padding: 12px; border-radius: 6px; overflow:auto }}
    .section {{ margin-bottom: 24px; }}
    .metrics-table td, .metrics-table th {{ padding:6px 8px; border:1px solid #ddd }}
    .metrics-table {{ border-collapse: collapse; width:100%; max-width:1000px }}
  </style>
</head>
<body>
  <h1>Clinical Trial Radar — Feasibility Snapshot</h1>
  <div class="section">
    <h2>Summary</h2>
    <p>Total studies analyzed: <strong>{n_total_studies}</strong></p>
  </div>
  <div class="section">
    <h2>Cycle time (days)</h2>
    <pre>{cycle_time}</pre>
  </div>
  <div class="section">
    <h2>Trend by start year</h2>
    {trend_table}
  </div>
  <div class="section">
    <h2>Crowdedness (top countries)</h2>
    {crowd_table}
  </div>
  <div class="section">
    <h2>Visualizations</h2>
    <ul>
      {viz_links}
    </ul>
  </div>
  <div class="section">
    <h2>Notes</h2>
    <p>Generated by Clinical Trial Radar Stage 1 prototype.</p>
  </div>
</body>
</html>
"""


def _to_table(records: List[Dict[str, Any]], max_rows: int = 20) -> str:
    if not records:
        return "<p>No data</p>"
    # build simple HTML table
    keys = list(records[0].keys())
    rows = records[:max_rows]
    th = ''.join(f"<th>{k}</th>" for k in keys)
    trs = ''
    for r in rows:
        tds = ''.join(f"<td>{r.get(k,'')}</td>" for k in keys)
        trs += f"<tr>{tds}</tr>\n"
    return f"<table class='metrics-table'><thead><tr>{th}</tr></thead><tbody>{trs}</tbody></table>"


def generate_snapshot(metrics: Any, viz_paths: Optional[Dict[str, str]] = None, out_html: str = 'snapshot.html') -> str:
    """Generate an HTML snapshot from metrics (dict or json path) and optional visualization paths.

    `metrics`: dict or path to JSON file produced by `ct_radar.metrics.save_metrics`
    `viz_paths`: dict with keys like 'trend','map','table' pointing to HTML/PNG files
    `out_html`: output HTML file path
    """
    if isinstance(metrics, str):
        if not os.path.exists(metrics):
            raise FileNotFoundError(metrics)
        with open(metrics, 'r', encoding='utf-8') as f:
            m = json.load(f)
    elif isinstance(metrics, dict):
        m = metrics
    else:
        raise ValueError('metrics must be a dict or path to JSON')

    trend = m.get('trend_by_start_year', [])
    crowd = m.get('crowdedness', [])
    cycle = m.get('cycle_time', {})

    trend_table = _to_table(trend)
    crowd_table = _to_table(crowd)
    cycle_str = json.dumps(cycle, indent=2, ensure_ascii=False)

    viz_links = ''
    if viz_paths:
        for k, p in viz_paths.items():
            if p:
                rel = os.path.relpath(p, os.path.dirname(out_html) or '.')
                viz_links += f"<li>{k}: <a href=\"{rel}\">{os.path.basename(p)}</a></li>"

    html = HTML_TEMPLATE.format(
        n_total_studies=m.get('n_total_studies', 0),
        cycle_time=cycle_str,
        trend_table=trend_table,
        crowd_table=crowd_table,
        viz_links=viz_links,
    )

    os.makedirs(os.path.dirname(out_html) or '.', exist_ok=True)
    with open(out_html, 'w', encoding='utf-8') as f:
        f.write(html)

    return out_html


try:
    from pptx import Presentation
    from pptx.util import Inches
except Exception:
    Presentation = None


def generate_snapshot_pptx(metrics: Any, image_paths: Optional[List[str]] = None, out_pptx: str = 'snapshot.pptx') -> Optional[str]:
    """Generate a simple PPTX containing metrics text and optional image slides. Requires python-pptx."""
    if Presentation is None:
        return None
    if isinstance(metrics, str):
        with open(metrics, 'r', encoding='utf-8') as f:
            m = json.load(f)
    else:
        m = metrics

    prs = Presentation()
    # title
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = 'Clinical Trial Radar — Snapshot'
    subtitle.text = f"Total studies: {m.get('n_total_studies',0)}"

    # metrics slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = 'Cycle time & trend'
    body = slide.shapes.placeholders[1].text_frame
    body.text = json.dumps(m.get('cycle_time', {}), indent=2, ensure_ascii=False)

    # images
    if image_paths:
        for img in image_paths:
            if os.path.exists(img):
                slide = prs.slides.add_slide(prs.slide_layouts[5])
                slide.shapes.title.text = os.path.basename(img)
                left = Inches(1)
                top = Inches(1.5)
                slide.shapes.add_picture(img, left, top, width=Inches(8))

    os.makedirs(os.path.dirname(out_pptx) or '.', exist_ok=True)
    prs.save(out_pptx)
    return out_pptx


__all__ = ["generate_snapshot", "generate_snapshot_pptx"]
